const colors = {
    backgroundColor : '#fff',
    primaryColor: '#00bbb1',
    transparent: 'transparent',
    headerBackgroundColor: '#00bbb1',
    loadingIndicatorBGColor: "rgba(0,0,0,0.4)",
    textInputBackgroundColor : '#fff',
    textInputColor : '#181818',
    textInputPlaceholderColor : '#181818',
    iconColor : '#181818',
    textColor : '#181818',
    chatIconColor : '#181818',
    chatInputBackGroundColor : 'transparent',
    tabbarBackgroundColor : '#fff',
    tabbarIconColor : '#171717',
    borderColor : '#171717',
    black: '#000',
    white: "#FFFFFF",
    textFieldColor : "#000",
    blueText : "#0000EE",
    grayColor : "#DCDCDC",
    redColor : "#FF6347",
};
export default colors;
