import { RFPercentage } from "react-native-responsive-fontsize"

const fonts = {
    fontSize_6: RFPercentage(0.005),
    fontSize_7: RFPercentage(0.75),
    fontSize_8: RFPercentage(1),
    fontSize_9: RFPercentage(1.25),
    fontSize_10: RFPercentage(1.5),
    fontSize_10_5: RFPercentage(1.67),
    fontSize_11: RFPercentage(1.75),
    fontSize_12: RFPercentage(2),
    fontSize_12_5: RFPercentage(2.15),
    fontSize_13: RFPercentage(2.3),
    fontSize_13_5: RFPercentage(2.4),
    fontSize_14: RFPercentage(2.5),
    fontSize_14_5: RFPercentage(2.6),
    fontSize_15: RFPercentage(2.75),
    fontSize_16: RFPercentage(3),
    fontSize_17: RFPercentage(3.25),
    fontSize_18: RFPercentage(3.5),
    fontSize_20: RFPercentage(4),
    fontSize_21: RFPercentage(4.25),
    fontSize_22: RFPercentage(4.5),
    fontSize_23: RFPercentage(4.75),
    fontSize_24: RFPercentage(5),
    fontSize_25: RFPercentage(5.25),
    fontSize_26: RFPercentage(5.5),
    fontSize_27: RFPercentage(5.75),
    fontSize_28: RFPercentage(6),

    // fontFamily_bold: Platform.OS === "ios" ? "SFProDisplay-Bold" : "SF-Pro-Display-Bold",
    // fontFamily_extra_bold: Platform.OS === "ios" ? "SFProDisplay-Heavy" : "SF-Pro-Display-Heavy",
    // fontFamily_light: Platform.OS === "ios" ? "SFProDisplay-Light" : "SF-Pro-Display-Light",
    // fontFamily_medium: Platform.OS === "ios" ? "SFProDisplay-Medium" : "SF-Pro-Display-Medium",
    // fontFamily_semi_bold: Platform.OS === "ios" ? "SFProDisplay-Semibold" : "SF-Pro-Display-Semibold",
    // fontFamily_regular: Platform.OS === "ios" ? "SFProDisplay-Regular" : "SF-Pro-Display-Regular",
    // fontFamily_thin: Platform.OS === "ios" ? "SFProDisplay-Thin" : "SF-Pro-Display-Thin",
    // fontFamily_italic: Platform.OS === "ios" ? "SFProDisplay-RegularItalic" : "SF-Pro-Display-RegularItalic"
}
export default fonts; 
